default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  adapter: postgresql
  encoding: unicode
  database: rails_vue_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *development
  database: rails_vue_test

production:
  url: <%= ENV['DATABASE_URL'] %>
